"""Initial migration with all models

Revision ID: a25089c31264
Revises: 
Create Date: 2025-07-04 11:01:53.129020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a25089c31264'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azure_dev_ops_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=100), nullable=False),
    sa.Column('pat_token', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_name')
    )
    op.create_table('monitored_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('monitored_ado_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('pool_name', sa.String(length=100), nullable=False),
    sa.Column('ado_config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ado_config_id'], ['azure_dev_ops_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitored_ado_pool')
    op.drop_table('setting')
    op.drop_table('monitored_group')
    op.drop_table('azure_dev_ops_config')
    # ### end Alembic commands ###
